[package]
name = "comic-fake-view"
version = "0.1.0"
edition = "2021"

[dependencies]
backon.workspace = true
chromiumoxide.workspace = true
color-eyre.workspace = true
futures.workspace = true
notify-rust.workspace = true
reqwest.workspace = true
tokio.workspace = true
