[package]
name = "chapter-fetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre.workspace = true
futures.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
