name: cli
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-chapter:
    runs-on: ubuntu-latest
    environment: production
    outputs:
      version: ${{ env.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Chromium
        uses: browser-actions/setup-chrome@v1
        with:
          install-dependencies: true
          chrome-version: stable

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          targets: x86_64-unknown-linux-gnu
          toolchain: nightly

      - name: Cache Rust dependencies and build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run
        shell: bash
        run: |
          cargo run --bin cli
        env:
          app_user_data_dir: ~/.chromium
          app_headless: true
          app_wait_for_navigation: 1
          app_max_retries: 3
          app_tab_count: 10
