name: cli
on:
  schedule:
     - cron: '0 17 * * *'    # local 00:00  → UTC 17:00 (previous day)
    - cron: '25 17 * * *'   # local 00:25  → UTC 17:25 (previous day)
    - cron: '50 17 * * *'   # local 00:50  → UTC 17:50 (previous day)
    - cron: '15 18 * * *'   # local 01:15  → UTC 18:15 (previous day)
    - cron: '40 18 * * *'   # local 01:40  → UTC 18:40 (previous day)
    - cron: '5 19 * * *'    # local 02:05  → UTC 19:05 (previous day)
    - cron: '30 19 * * *'   # local 02:30  → UTC 19:30 (previous day)
    - cron: '55 19 * * *'   # local 02:55  → UTC 19:55 (previous day)
    - cron: '20 20 * * *'   # local 03:20  → UTC 20:20 (previous day)
    - cron: '45 20 * * *'   # local 03:45  → UTC 20:45 (previous day)
    - cron: '10 21 * * *'   # local 04:10  → UTC 21:10 (previous day)
    - cron: '35 21 * * *'   # local 04:35  → UTC 21:35 (previous day)
    - cron: '0 22 * * *'    # local 05:00  → UTC 22:00 (previous day)
    - cron: '25 22 * * *'   # local 05:25  → UTC 22:25 (previous day)
    - cron: '50 22 * * *'   # local 05:50  → UTC 22:50 (previous day)
    - cron: '15 23 * * *'   # local 06:15  → UTC 23:15 (previous day)
    - cron: '40 23 * * *'   # local 06:40  → UTC 23:40 (previous day)
    - cron: '5 0 * * *'     # local 07:05  → UTC 00:05 (same day)
    - cron: '30 0 * * *'    # local 07:30  → UTC 00:30 (same day)
    - cron: '55 0 * * *'    # local 07:55  → UTC 00:55 (same day)
    - cron: '20 1 * * *'    # local 08:20  → UTC 01:20 (same day)
    - cron: '45 1 * * *'    # local 08:45  → UTC 01:45 (same day)
    - cron: '10 2 * * *'    # local 09:10  → UTC 02:10 (same day)
    - cron: '35 2 * * *'    # local 09:35  → UTC 02:35 (same day)
    - cron: '0 3 * * *'     # local 10:00  → UTC 03:00 (same day)
    - cron: '25 3 * * *'    # local 10:25  → UTC 03:25 (same day)
    - cron: '50 3 * * *'    # local 10:50  → UTC 03:50 (same day)
    - cron: '15 4 * * *'    # local 11:15  → UTC 04:15 (same day)
    - cron: '40 4 * * *'    # local 11:40  → UTC 04:40 (same day)
    - cron: '5 5 * * *'     # local 12:05  → UTC 05:05 (same day)
    - cron: '30 5 * * *'    # local 12:30  → UTC 05:30 (same day)
    - cron: '55 5 * * *'    # local 12:55  → UTC 05:55 (same day)
    - cron: '20 6 * * *'    # local 13:20  → UTC 06:20 (same day)
    - cron: '45 6 * * *'    # local 13:45  → UTC 06:45 (same day)
    - cron: '10 7 * * *'    # local 14:10  → UTC 07:10 (same day)
    - cron: '35 7 * * *'    # local 14:35  → UTC 07:35 (same day)
    - cron: '0 8 * * *'     # local 15:00  → UTC 08:00 (same day)
    - cron: '25 8 * * *'    # local 15:25  → UTC 08:25 (same day)
    - cron: '50 8 * * *'    # local 15:50  → UTC 08:50 (same day)
    - cron: '15 9 * * *'    # local 16:15  → UTC 09:15 (same day)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-chapter:
    runs-on: ubuntu-latest
    environment: cli
    outputs:
      version: ${{ env.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Chromium
        uses: browser-actions/setup-chrome@v1
        with:
          install-dependencies: true
          chrome-version: stable

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          targets: x86_64-unknown-linux-gnu
          toolchain: nightly

      - name: Cache Rust dependencies and build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run
        shell: bash
        run: |
          cargo run --bin cli
        env:
          app_user_data_dir: ${{ vars.USER_DATA_DIR }}
          app_headless: true
          app_wait_for_navigation: ${{ vars.WAIT_FOR_NAVIGATION }}
          app_max_retries: ${{ vars.MAX_RETRIES }}
          app_tab_count: ${{ vars.TAB_COUNT }}
