name: cli
on:
  schedule:
    - cron: '0 17 * * *'    # local 00:00 (UTC+7) → 17:00 UTC (previous day)
    - cron: '23 17 * * *'   # local 00:23 → 17:23 UTC (previous day)
    - cron: '46 17 * * *'   # local 00:46 → 17:46 UTC (previous day)
    - cron: '9 18 * * *'    # local 01:09 → 18:09 UTC
    - cron: '32 18 * * *'   # local 01:32 → 18:32 UTC
    - cron: '55 18 * * *'   # local 01:55 → 18:55 UTC
    - cron: '18 19 * * *'   # local 02:18 → 19:18 UTC
    - cron: '41 19 * * *'   # local 02:41 → 19:41 UTC
    - cron: '4 20 * * *'    # local 03:04 → 20:04 UTC
    - cron: '27 20 * * *'   # local 03:27 → 20:27 UTC
    - cron: '50 20 * * *'   # local 03:50 → 20:50 UTC
    - cron: '13 21 * * *'   # local 04:13 → 21:13 UTC
    - cron: '36 21 * * *'   # local 04:36 → 21:36 UTC
    - cron: '59 21 * * *'   # local 04:59 → 21:59 UTC
    - cron: '22 22 * * *'   # local 05:22 → 22:22 UTC
    - cron: '45 22 * * *'   # local 05:45 → 22:45 UTC
    - cron: '8 23 * * *'    # local 06:08 → 23:08 UTC
    - cron: '31 23 * * *'   # local 06:31 → 23:31 UTC
    - cron: '54 23 * * *'   # local 06:54 → 23:54 UTC
    - cron: '17 0 * * *'    # local 07:17 → 00:17 UTC (next day)
    - cron: '40 0 * * *'    # local 07:40 → 00:40 UTC (next day)
    - cron: '3 1 * * *'     # local 08:03 → 01:03 UTC (next day)
    - cron: '26 1 * * *'    # local 08:26 → 01:26 UTC (next day)
    - cron: '49 1 * * *'    # local 08:49 → 01:49 UTC (next day)
    - cron: '12 2 * * *'    # local 09:12 → 02:12 UTC (next day)
    - cron: '35 2 * * *'    # local 09:35 → 02:35 UTC (next day)
    - cron: '58 2 * * *'    # local 09:58 → 02:58 UTC (next day)
    - cron: '21 3 * * *'    # local 10:21 → 03:21 UTC (next day)
    - cron: '44 3 * * *'    # local 10:44 → 03:44 UTC (next day)
    - cron: '7 4 * * *'     # local 11:07 → 04:07 UTC (next day)
    - cron: '30 4 * * *'    # local 11:30 → 04:30 UTC (next day)
    - cron: '53 4 * * *'    # local 11:53 → 04:53 UTC (next day)
    - cron: '16 5 * * *'    # local 12:16 → 05:16 UTC (next day)
    - cron: '39 5 * * *'    # local 12:39 → 05:39 UTC (next day)
    - cron: '2 6 * * *'     # local 13:02 → 06:02 UTC (next day)
    - cron: '25 6 * * *'    # local 13:25 → 06:25 UTC (next day)
    - cron: '48 6 * * *'    # local 13:48 → 06:48 UTC (next day)
    - cron: '11 7 * * *'    # local 14:11 → 07:11 UTC (next day)
    - cron: '34 7 * * *'    # local 14:34 → 07:34 UTC (next day)
    - cron: '57 7 * * *'    # local 14:57 → 07:57 UTC (next day)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-chapter:
    runs-on: ubuntu-latest
    environment: cli
    outputs:
      version: ${{ env.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Chromium
        uses: browser-actions/setup-chrome@v1
        with:
          install-dependencies: true
          chrome-version: stable

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          targets: x86_64-unknown-linux-gnu
          toolchain: nightly

      - name: Cache Rust dependencies and build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run
        shell: bash
        run: |
          cargo run --bin cli
        env:
          app_user_data_dir: ${{ vars.USER_DATA_DIR }}
          app_headless: true
          app_wait_for_navigation: ${{ vars.WAIT_FOR_NAVIGATION }}
          app_max_retries: ${{ vars.MAX_RETRIES }}
          app_tab_count: ${{ vars.TAB_COUNT }}
